image: docker:latest

services:
  - docker:dind

stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: collinsmunufie/flask-ci-cd-demo

before_script:
  - docker login -u "collinsmunufie" -p "Kophi!@2018"

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE
